### ISSUE TITLE
Error when running demo.py with custom dataset

### ISSUE THREAD

**Issue by xtcpete** [facebookresearch/vggsfm#10]
When I tried to run the demo with my custom dataset containing 15 frames, the following error occurred. However, when I reduced the number of frames to 10, the error disappeared.

Traceback (most recent call last):
  File "/data/home/gochen/gonglinc/vggsfm/demo.py", line 122, in test_fn
    predictions = run_one_scene(
  File "/data/home/gochen/gonglinc/vggsfm/demo.py", line 290, in run_one_scene
    BA_cameras, extrinsics_opencv, intrinsics_opencv, points3D, reconstruction = triangulator(
  File "/home/gochen/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gochen/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/gochen/gonglinc/vggsfm/vggsfm/models/triangulator.py", line 191, in forward
    best_triangulated_points, best_inlier_num, best_inlier_mask = triangulate_tracks(
  File "/data/home/gochen/gonglinc/vggsfm/vggsfm/utils/triangulation.py", line 396, in triangulate_tracks
    triangulated_points, tri_angles, invalid_che_mask = triangulate_multi_view_point_batched(
  File "/data/home/gochen/gonglinc/vggsfm/vggsfm/utils/triangulation_helpers.py", line 48, in triangulate_multi_view_point_batched
    eigenvalues, eigenvectors = torch.linalg.eigh(A)
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_INVALID_VALUE, when calling `cusolverDnDsyevjBatched_bufferSize( handle, jobz, uplo, n, A, lda, W, lwork, params, batchsize)`. This error may appear if the input matrix contains NaN. If you keep seeing this error, you may use `torch.backends.cuda.preferred_linalg_library()` to try linear algebra operators with other supported backends. See https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.preferred_linalg_library

**Comment by jytime** [comment]
Hi,

It seems the matrix for triangulation does not hold a good condition. I guess there are some special images in the removed 5 frames. If possible, you can share your images here or send them to my email, and I will have a look at them.

**Comment by xtcpete** [comment]
Hi,

Thanks for getting back so quickly and this is really great work!. It seems to be an environment issue. The error occurred on an A40 GPU, but I was unable to reproduce it on an A100. I managed to get it running, so I will close this issue.

**Comment by xtcpete** [comment]
Hi,

Thanks for getting back to me so quickly. I did some more testing and found that it is related to the query_frame_num parameter. Setting it to 3 works fine, but setting it to 5 throws an error. I have sent the dataset to your email. Thanks.

**Comment by jytime** [comment]
ah I see. Looking at the images I know why it works weird now. I think we need to expose more flags so people can deal with such data. I should be able to update the code this weekend.

**Comment by jytime** [comment]
Hi I am a bit busy with cvpr stuffs this week, and should catch up after the conference

**Comment by xtcpete** [comment]
Hi, no worries. Looking forward to hearing from you.

**Comment by jytime** [comment]
<img width="1155" alt="Screenshot 2024-06-24 at 02 43 49" src="https://github.com/facebookresearch/vggsfm/assets/37647961/9302ff6b-5722-4e03-83fa-9e74c7645d33">


Hi @xtcpete , in our new memory-efficient version, the reconstruction for your images looks like this. It seems correct to me. Does this look good to you?

**Comment by xtcpete** [comment]
Hi,

This looks good to me. Your work is very impressive! Do you have an estimated release date for this new version? Thank you so much.

**Comment by jytime** [comment]
Hi @xtcpete could you please try the updated version? Since we have updated a lot, please re-clone the repository and follow the instructions step by step. By running ```python demo.py SCENE_DIR=examples/YOUR_FOLDER visualize=True ``` it should give you something like below in the visdom server.



<img width="1156" alt="Screenshot 2024-06-25 at 05 22 55" src="https://github.com/facebookresearch/vggsfm/assets/37647961/dd5907b7-eb05-4579-bc3e-bb452422f1b6">


Or if you don't mind, I can add your scene as one more example for the ```examples``` folder.

**Comment by wujiiie** [comment]
hi，i run this demo has same error，

Error executing job with overrides: ['SCENE_DIR=examples/kitchen']
Traceback (most recent call last):
  File "/tmp/algorithm/cosmos-predict2.5-main/test/vggsfm-main/vggsfm-main/demo.py", line 71, in demo_fn
    predictions = vggsfm_runner.run(
  File "/tmp/algorithm/cosmos-predict2.5-main/test/vggsfm-main/vggsfm-main/vggsfm/runners/runner.py", line 229, in run
    predictions = self.sparse_reconstruct(
  File "/tmp/algorithm/cosmos-predict2.5-main/test/vggsfm-main/vggsfm-main/vggsfm/runners/runner.py", line 501, in sparse_reconstruct
    ) = self.triangulator(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/algorithm/cosmos-predict2.5-main/test/vggsfm-main/vggsfm-main/vggsfm/models/triangulator.py", line 127, in forward
    triangulate_by_pair(extrinsics[None], tracks_normalized[None])
  File "/tmp/algorithm/cosmos-predict2.5-main/test/vggsfm-main/vggsfm-main/vggsfm/utils/triangulation.py", line 81, in triangulate_by_pair
    points_3d_pair, cheirality_mask = triangulate_multi_view_point_from_tracks(
  File "/tmp/algorithm/cosmos-predict2.5-main/test/vggsfm-main/vggsfm-main/vggsfm/utils/triangulation.py", line 666, in triangulate_multi_view_point_from_tracks
    triangulate_multi_view_point_batched(
  File "/tmp/algorithm/cosmos-predict2.5-main/test/vggsfm-main/vggsfm-main/vggsfm/utils/triangulation_helpers.py", line 87, in triangulate_multi_view_point_batched
    _, eigenvectors = torch.linalg.eigh(A)
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_INVALID_VALUE, when calling `cusolverDnXsyevBatched_bufferSize( handle, params, jobz, uplo, n, CUDA_R_64F, reinterpret_cast<const void*>(A), lda, CUDA_R_64F, reinterpret_cast<const void*>(W), CUDA_R_64F, workspaceInBytesOnDevice, workspaceInBytesOnHost, batchSize)`. This error may appear if the input matrix contains NaN. If you keep seeing this error, you may use `torch.backends.cuda.preferred_linalg_library()` to try linear algebra operators with other supported backends. See https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.preferred_linalg_library

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
