### ISSUE TITLE
test.py error

### ISSUE THREAD

**Issue by 1511607288** [facebookresearch/vggsfm#14]
When i tried to run test.py, it showed problems like this：
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/jm/vggsfm/vggsfm-main/demo.py", line 365, in <module>
    test_fn()
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jm/vggsfm/vggsfm-main/demo.py", line 82, in test_fn
    batch, image_paths = test_dataset.get_data(sequence_name=seq_name, return_path=True)
  File "/home/jm/vggsfm/vggsfm-main/vggsfm/datasets/sequence_loader.py", line 286, in get_data
    batch["crop_params"] = torch.stack(crop_parameters)
RuntimeError: stack expects a non-empty TensorList

**Comment by jytime** [comment]
Hey this means the path of IMC dataset (test set) is not set correctly or the folders are not structed as expected. Please first check if you set the test dataset path correctly in `test.yaml`:

https://github.com/facebookresearch/vggsfm/blob/7dc711d05d2db3be5847d02d1aba06fccea16a8d/cfgs/test.yaml#L8


Then check here for how the folders of IMC dataset should be structured as:
https://github.com/facebookresearch/vggsfm/blob/7dc711d05d2db3be5847d02d1aba06fccea16a8d/vggsfm/datasets/imc.py#L58-L70

**Comment by 1511607288** [comment]
Thank you for your help, sorry for answering you so late, and this error has fixed ,but an new error occurred:
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/jm/vggsfm/vggsfm-main/test.py", line 315, in <module>
    test_fn()
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jm/vggsfm/vggsfm-main/test.py", line 104, in test_fn
    predictions = run_one_scene(
  File "/home/jm/vggsfm/vggsfm-main/test.py", line 204, in run_one_scene
    fine_pred_track, _, pred_vis, pred_score = track_predictor(images_feed, query_points, fmaps=fmaps_feed)
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jm/vggsfm/vggsfm-main/vggsfm/models/track_predictor.py", line 56, in forward
    coarse_pred_track_lists, pred_vis = self.coarse_predictor(
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jm/vggsfm/vggsfm-main/vggsfm/models/track_modules/base_track_predictor.py", line 126, in forward
    fcorrs = fcorr_fn.sample(coords)  # B, S, N, corrdim
  File "/home/jm/vggsfm/vggsfm-main/vggsfm/models/track_modules/blocks.py", line 301, in sample
    corrs = bilinear_sampler(corrs.reshape(B * S * N, 1, H, W), coords_lvl, padding_mode=self.padding_mode)
  File "/home/jm/vggsfm/vggsfm-main/vggsfm/models/utils.py", line 277, in bilinear_sampler
    return F.grid_sample(input, coords, align_corners=align_corners, padding_mode=padding_mode)
  File "/home/jm/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/functional.py", line 4304, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.50 GiB. GPU 0 has a total capacty of 7.76 GiB of which 1.70 GiB is free. Including non-PyTorch memory, this process has 5.45 GiB memory in use. Of the allocated memory 4.19 GiB is allocated by PyTorch, and 1.05 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
and my GPU is 3070ti laptop 8G, can  this GPU run vggsfm or not?

**Comment by jytime** [comment]
Hi it depends on how many frames do you want to reconstruct. I have updated the repo to a memory-efficient version. Feel free to have a try again. Reduce ```max_query_pts``` if necessary.
