### ISSUE TITLE
Exception when running with dense_depth=True

### ISSUE THREAD

**Issue by nickponline** [facebookresearch/vggsfm#29]
Command
` python demo.py visualize=True SCENE_DIR=examples/house resume_ckpt=./vggsfm_v2_0_0.bin query_frame_num=4 max_query_pts=2048 dense_depth=True`

Input 30 images https://www.dropbox.com/s/o4hneo8h295f9wn/images.zip?dl=0

```
Error executing job with overrides: ['visualize=True', 'SCENE_DIR=examples/house', 'resume_ckpt=./vggsfm_v2_0_0.bin', 'query_frame_num=4', 'max_query_pts=2048', 'dense_depth=True']
Traceback (most recent call last):
  File "/home/nickp/vggsfm/demo.py", line 132, in demo_fn
    predictions = run_one_scene(
  File "/home/nickp/vggsfm/demo.py", line 200, in run_one_scene
    disp_map = depth_model.infer_image(
  File "/home/nickp/miniconda3/envs/vggsfm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dpt.py", line 190, in infer_image
    depth = self.forward(image)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dpt.py", line 179, in forward
    features = self.pretrained.get_intermediate_layers(x, self.intermediate_layer_idx[self.encoder], return_class_token=True)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dinov2.py", line 308, in get_intermediate_layers
    outputs = self._get_intermediate_layers_not_chunked(x, n)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dinov2.py", line 277, in _get_intermediate_layers_not_chunked
    x = blk(x)
  File "/home/nickp/miniconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nickp/miniconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dinov2_layers/block.py", line 247, in forward
    return super().forward(x_or_x_list)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dinov2_layers/block.py", line 105, in forward
    x = x + attn_residual_func(x)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dinov2_layers/block.py", line 84, in attn_residual_func
    return self.ls1(self.attn(self.norm1(x)))
  File "/home/nickp/miniconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nickp/miniconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dinov2_layers/attention.py", line 69, in forward
    return super().forward(x)
  File "/home/nickp/vggsfm/dependency/depth_any_v2/depth_anything_v2/dinov2_layers/attention.py", line 54, in forward
    attn = q @ k.transpose(-2, -1)
RuntimeError: handle_0 INTERNAL ASSERT FAILED at "/home/conda/feedstock_root/build_artifacts/libtorch_1705951428005/work/c10/cuda/driver_api.cpp":15, please report a bug to PyTorch.
```

**Comment by jytime** [comment]
It looks like your input images are too large (~4000x3000), and depth anything V2 model cannot deal with such large images. I’ve made a quick fix to the demo file, setting the max input size for the depth estimation model to 1024. This might result in some loss of detail, but it should now work.
https://github.com/facebookresearch/vggsfm/commit/9263351e7591a45139944f9a829ebd872bd6760e
