### ISSUE TITLE
How to obtain the pose or transforms of the cameras as a .json document

### ISSUE THREAD

**Issue by jianghr-shanghaitech** [facebookresearch/vggsfm#40]

**Comment by jianghr-shanghaitech** [comment]
By the way, I encountered this error when using the demo.py
![捕获](https://github.com/user-attachments/assets/f0942dff-7d4d-4318-8b0c-a1d2da3870bf)

**Comment by jianghr-shanghaitech** [comment]
Poselib is available
Poselib is available
/home/jianghr/vggsfm/demo.py:58: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="cfgs/", config_name="demo")
/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Model Config: seed: 0
img_size: 1024
viz_ip: 127.0.0.1
debug: false
center_order: true
mixed_precision: fp16
extract_color: true
filter_invalid_frame: true
comple_nonvis: true
query_frame_num: 3
robust_refine: 2
BA_iters: 1
camera_type: SIMPLE_PINHOLE
load_gt: false
visualize: false
fmat_thres: 4.0
max_reproj_error: 4.0
init_max_reproj_error: 4.0
max_query_pts: 2048
dense_depth: false
shared_camera: true
SCENE_DIR: examples/statue
resume_ckpt: /PATH/YOUR/CKPT
query_by_interval: false
query_method: sp+sift
use_poselib: true
make_reproj_video: false
visual_depths: false
visual_query_points: false
visual_dense_point_cloud: false
MODEL:
  _target_: vggsfm.models.VGGSfM
  TRACK:
    _target_: vggsfm.models.TrackerPredictor
    efficient_corr: false
    COARSE:
      stride: 4
      down_ratio: 2
      FEATURENET:
        _target_: vggsfm.models.BasicEncoder
      PREDICTOR:
        _target_: vggsfm.models.BaseTrackerPredictor
    FINE:
      FEATURENET:
        _target_: vggsfm.models.ShallowEncoder
      PREDICTOR:
        _target_: vggsfm.models.BaseTrackerPredictor
        depth: 4
        corr_levels: 3
        corr_radius: 3
        latent_dim: 32
        hidden_size: 256
        fine: true
        use_spaceatt: false
  CAMERA:
    _target_: vggsfm.models.CameraPredictor
  TRIANGULAE:
    _target_: vggsfm.models.Triangulator

Error executing job with overrides: ['SCENE_DIR=examples/statue', 'resume_ckpt=/PATH/YOUR/CKPT', 'shared_camera=True', 'query_method=sp+sift']
Traceback (most recent call last):
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/jianghr/vggsfm/vggsfm/models/camera_predictor.py", line 61, in __init__
    self.backbone = self.get_backbone(backbone)
  File "/home/jianghr/vggsfm/vggsfm/models/camera_predictor.py", line 174, in get_backbone
    return torch.hub.load("facebookresearch/dinov2", "dinov2_vitb14_reg")
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/hub.py", line 563, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/hub.py", line 230, in _get_cache_or_reload
    _validate_not_a_forked_repo(repo_owner, repo_name, ref)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/hub.py", line 189, in _validate_not_a_forked_repo
    response = json.loads(_read_url(Request(url, headers=headers)))
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/hub.py", line 172, in _read_url
    with urlopen(url) as r:
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/jianghr/vggsfm/vggsfm/models/vggsfm.py", line 32, in __init__
    self.camera_predictor = instantiate(CAMERA, _recursive_=False, cfg=cfg)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'vggsfm.models.camera_predictor.CameraPredictor':
<HTTPError 401: 'Unauthorized'>
full_key: CAMERA

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jianghr/vggsfm/demo.py", line 641, in <module>
    demo_fn()
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jianghr/vggsfm/demo.py", line 73, in demo_fn
    model = instantiate(cfg.MODEL, _recursive_=False, cfg=cfg)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'vggsfm.models.vggsfm.VGGSfM':
InstantiationException("Error in call to target 'vggsfm.models.camera_predictor.CameraPredictor':\n<HTTPError 401: 'Unauthorized'>\nfull_key: CAMERA")
full_key: MODEL

**Comment by jianghr-shanghaitech** [comment]
[transforms.json](https://github.com/user-attachments/files/16429962/transforms.json)
like this kind of json
