### ISSUE TITLE
Cannot read dense depth binary

### ISSUE THREAD

**Issue by aashutoshpy** [facebookresearch/vggsfm#80]
I am trying to use the dense depth exported in COLMAP format for gaussian splatting. COLMAP crashes with `std::bad_alloc` while trying to read the binary.
```terminate called after throwing an instance of 'std::bad_alloc'                                                                                                                         
  what():  std::bad_alloc
*** Aborted at 1731038745 (unix time) try "date -d @1731038745" if you are using GNU date ***
PC: @     0x7da995c969fc pthread_kill
*** SIGABRT (@0x3e800001088) received by PID 4232 (TID 0x7da8abe00000) from PID 4232; stack trace: ***
    @     0x7da995c99ee8 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x99ee7)
    @     0x7da9980fc917 google::(anonymous namespace)::FailureSignalHandler(int, siginfo*, void*)
    @     0x7da995c42520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
    @     0x7da995c969fc pthread_kill
    @     0x7da995c42476 raise
    @     0x7da995c287f3 abort
    @     0x7da9960d5fae __gnu_cxx::__verbose_terminate_handler()
    @     0x7da9960d44f2 __cxxabiv1::__terminate(void (*)())
    @     0x7da9960ce2f3 std::terminate()
    @     0x7da9960d4712 __cxa_throw
    @     0x7da9960d4b3f operator new(unsigned long)
    @     0x6320cf66c421 void std::vector<colmap::TrackElement, std::allocator<colmap::TrackElement> >::_M_realloc_insert<unsigned int const&, unsigned int const&>(__gnu_cxx::__normal_iterator<colmap::TrackElement*, std::vector<colmap::TrackElement, std::allocator<colmap::TrackEle��
    @     0x6320cf66c758 colmap::ReadPoints3DBinary(colmap::Reconstruction&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    @     0x6320cf65f430 colmap::Reconstruction::ReadBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    @     0x6320cf678da6 colmap::ReconstructionManager::Read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    @     0x6320cf78939d std::_Function_handler<void (), colmap::MainWindow::Import()::{lambda()#1}>::_M_invoke(std::_Any_data const&)
    @     0x6320cf6b1734 colmap::Thread::RunFunc()
    @     0x7da9960f1b65 execute_native_thread_routine
    @     0x7da995c94ac3 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x94ac2)
    @     0x7da995d26850 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x12684f)
Aborted (core dumped)
```

I tried to convert the data to nerfstudio format using `ns-process-data`, this is throwing the following error.
```
Traceback (most recent call last):
  File "/home/fm-pc-lt-288/anaconda3/envs/nerfstudio/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/fm-pc-lt-288/anaconda3/envs/nerfstudio/lib/python3.11/site-packages/nerfstudio/scripts/process_data.py", line 550, in entrypoint
    tyro.cli(Commands).main()
  File "/home/fm-pc-lt-288/anaconda3/envs/nerfstudio/lib/python3.11/site-packages/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 125, in main
    summary_log += self._save_transforms(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fm-pc-lt-288/anaconda3/envs/nerfstudio/lib/python3.11/site-packages/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py", line 136, in _save_transforms
    num_matched_frames = colmap_utils.colmap_to_json(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fm-pc-lt-288/anaconda3/envs/nerfstudio/lib/python3.11/site-packages/nerfstudio/process_data/colmap_utils.py", line 483, in colmap_to_json
    create_ply_from_colmap(
  File "/home/fm-pc-lt-288/anaconda3/envs/nerfstudio/lib/python3.11/site-packages/nerfstudio/process_data/colmap_utils.py", line 682, in create_ply_from_colmap
    colmap_points = read_points3D_binary(recon_dir / "points3D.bin")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fm-pc-lt-288/anaconda3/envs/nerfstudio/lib/python3.11/site-packages/nerfstudio/data/utils/colmap_parsing_utils.py", line 354, in read_points3D_binary
    track_elems = read_next_bytes(fid, num_bytes=8 * track_length, format_char_sequence="ii" * track_length)
                                                                                        ~~~~~^~~~~~~~~~~~~~
OverflowError: cannot fit 'int' into an index-sized integer
```
 
Is there a way to make this dense points file work as `points3D.bin`?

**Comment by aashutoshpy** [comment]
I see that it predicts depth for every pixel instead
