### ISSUE TITLE
Problem on pycolmap

### ISSUE THREAD

**Issue by yyfz** [facebookresearch/vggsfm#85]
Hi, thanks for your great work! I install pycolmap using `pip install pycolmap==3.10.0 pyceres` but I encountered the following issue:

```python
Python 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycolmap
>>> ba_options_tmp = pycolmap.BundleAdjustmentOptions()
>>> ba_options_tmp.solver_options
TypeError: Unregistered type : ceres::Solver::Options

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: pycolmap.BundleAdjustmentOptions) -> ceres::Solver::Options
>>> ba_options_tmp.solver_options.function_tolerance *= 10
TypeError: Unregistered type : ceres::Solver::Options

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: pycolmap.BundleAdjustmentOptions) -> ceres::Solver::Options 
>>> import pycolmap
>>> import pyceres
>>> pycolmap.__version__
'3.10.0'
>>> pyceres.__version__
'2.3'
```

**Comment by yyfz** [comment]
I have resolved this issue with the help of pycolmap developer from [here](https://github.com/colmap/colmap/issues/2937).

**Comment by Mlynnray** [comment]
can you tell me how your \envs\vggsfm\Lib\site-packages composed， why I switch it to 2.3 didn't work

**Comment by yyfz** [comment]
> can you tell me how your \envs\vggsfm\Lib\site-packages composed， why I switch it to 2.3 didn't work

You can try importing pyceres first.
